{% set version = "0.7.5" %}

package:
  name: pickleshare
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pickleshare/pickleshare-{{ version }}.tar.gz
  sha256: 87683d47965c1da65cdacaf31c8441d12b8044cdec9aca500cd78fc2c683afca

build:
  number: 1004
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pickleshare
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pickleshare/pickleshare/
  license: MIT
  license_file: LICENSE
  summary: "Tiny 'shelve'-like database with concurrency support"

extra:
  recipe-maintainers:
    - pelson
    - takluyver
    - ocefpaf
    - Carreau
